language: ruby
cache: bundler
sudo: false
rvm:
#  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - 2.3.3
  - 2.4.0
#  - ruby-head
gemfile:
  - gemfiles/rails_3_0.gemfile
  - gemfiles/rails_3_1.gemfile
  - gemfiles/rails_3_2.gemfile
  - gemfiles/rails_4_0.gemfile
  - gemfiles/rails_4_1.gemfile
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_5_0.gemfile
matrix:
  allow_failures:
#    - rvm: ruby-head
#    - rvm: 1.9
  exclude:
    - rvm: 1.9
      gemfile: gemfiles/rails_3_2.gemfile
    - rvm: 1.9
      gemfile: gemfiles/rails_4_0.gemfile
    - rvm: 1.9
      gemfile: gemfiles/rails_4_1.gemfile
    - rvm: 1.9
      gemfile: gemfiles/rails_4_2.gemfile
    - rvm: 1.9
      gemfile: gemfiles/rails_5_0.gemfile
    - rvm: 2.0
      gemfile: gemfiles/rails_3_0.gemfile
    - rvm: 2.0
      gemfile: gemfiles/rails_3_1.gemfile
    - rvm: 2.0
      gemfile: gemfiles/rails_4_2.gemfile
    - rvm: 2.0
      gemfile: gemfiles/rails_5_0.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails_3_0.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails_3_1.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails_4_2.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails_5_0.gemfile
    - rvm: 2.2
      gemfile: gemfiles/rails_3_0.gemfile
    - rvm: 2.2
      gemfile: gemfiles/rails_3_1.gemfile
    - rvm: 2.2
      gemfile: gemfiles/rails_5_0.gemfile
    - rvm: 2.3.3
      gemfile: gemfiles/rails_3_0.gemfile
    - rvm: 2.3.3
      gemfile: gemfiles/rails_3_1.gemfile
    - rvm: 2.4.0
      gemfile: gemfiles/rails_3_0.gemfile
    - rvm: 2.4.0
      gemfile: gemfiles/rails_3_1.gemfile
    - rvm: 2.4.0
      gemfile: gemfiles/rails_3_2.gemfile
#    - rvm: ruby-head
#      gemfile: gemfiles/rails_5_0.gemfile
#  include:
#    - rvm: 1.9
#      gemfile: gemfiles/rails_3_0.gemfile
#    - rvm: 1.9
#      gemfile: gemfiles/rails_3_1.gemfile
before_install:
  - gem update --system
  - gem install bundler
install:
  - bundle install
