before_install:
  - gem update --system
  - gem install bundler
install:
  - bundle install

bundler_args: --no-deployment --jobs 3 --retry 3

cache: bundler

env:
  global:
    - JRUBY_OPTS="-Xcli.debug=true --debug"

language: ruby
sudo: false

rvm:
  - jruby-9.1.16.0
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - jruby-head
  - ruby-head
  - rbx-3

gemfile:
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_5_1.gemfile

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: rbx-3
  fast_finish: true
  exclude:
    - rvm: jruby-9.1.16.0
      gemfile: gemfiles/rails_4_2.gemfile
    - rvm: jruby-9.1.16.0
      gemfile: gemfiles/rails_5_0.gemfile
    - rvm: 2.5.0
      gemfile: gemfiles/rails_4_2.gemfile
    - rvm: jruby-head
      gemfile: gemfiles/rails_4_2.gemfile
    - rvm: jruby-head
      gemfile: gemfiles/rails_5_0.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_4_2.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_5_0.gemfile
    - rvm: rbx-3
      gemfile: gemfiles/rails_4_2.gemfile
    - rvm: rbx-3
      gemfile: gemfiles/rails_5_0.gemfile
